services:
  - type: web
    name: assurley-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production

  - type: web
    name: assurley-frontend
    env: static
    buildCommand: npm run build && sed -i "s|http://localhost:8000|${ASSURLEY_API_URL}|g" dist/config.js
    staticPublishPath: frontend/dist
    plan: free
    envVars:
      - key: ASSURLEY_API_URL
        fromService:
          type: web
          name: assurley-backend
          envVarKey: RENDER_EXTERNAL_URL
